services:
  drop-off:
    image: antoszka/drop-off # or ghcr.io/antoszka/drop-off
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - TRUST_PROXY=false # Set to true if a reverse proxy is in front of the container
    volumes:
      - "./data:/opt/app/backend/data"
      - "./data/images:/opt/app/frontend/public/img"
  #      - "./config.yaml:/opt/app/config.yaml" # Add this line, if you want to configure drop-off via config file and not via UI

  # To add ClamAV, to scan your shares for malicious files, 
  # see https://antoszka.github.io/drop-off/setup/integrations/#clamav-docker-only
